// Code generated by gen_consts. DO NOT EDIT.
// 配置文件: config/props.json

package main

// 属性标识符常量
const (
	PROP_LEVEL             = 1    // 等级
	PROP_STR               = 2    // 力量
	PROP_AGI               = 3    // 敏捷
	PROP_INT               = 4    // 智力
	PROP_STA               = 5    // 耐力
	PROP_ATK               = 101  // 攻击力 (公式: LinearAttack) [依赖: [2 3]]
	PROP_HP                = 102  // 最大生命 (公式: MaxHP) [依赖: [5]]
	PROP_DEF               = 103  // 防御力 (公式: Defense) [依赖: [5 2]]
	PROP_POWER             = 201  // 战斗力 (公式: CombatPower) [依赖: [101 102 103]]
	PROP_EXP               = 1001 // 经验值
	PROP_GOLD              = 1002 // 金币
	PROP_REP               = 1003 // 声望
	PROP_FATIGUE           = 1004 // 疲劳值
	PROP_EXP_BONUS         = 1101 // 经验加成 (公式: Sum) [依赖: [1003]]
	PROP_DROP_EXP          = 2001 // 掉落经验
	PROP_DROP_GOLD         = 2002 // 掉落金币
	PROP_MONSTER_TYPE      = 2003 // 怪物类型
	PROP_RESPAWN_TIME      = 2004 // 刷新时间
	PROP_THREAT_LEVEL      = 2101 // 威胁等级 (公式: Sum) [依赖: [201 2003]]
	PROP_NPC_TYPE          = 3001 // NPC类型
	PROP_DIALOG            = 3002 // 对话ID
	PROP_QUEST             = 3003 // 任务ID
	PROP_FRIEND            = 3004 // 友好度
	PROP_INTERACT_COOLDOWN = 3101 // 交互冷却 (公式: Sum) [依赖: [3004]]
)
